INSERT INTO drivers (name, pilotNumber, team, nationality) VALUES
('Max Verstappen', 1, 'Red Bull Racing', 'NED'),
('Sergio Perez', 11, 'Red Bull Racing', 'MEX'),
('Lewis Hamilton', 44, 'Mercedes', 'GBR'),
('George Russell', 63, 'Mercedes', 'GBR'),
('Charles Leclerc', 16, 'Ferrari', 'MON'),
('Carlos Sainz', 55, 'Ferrari', 'ESP'),
('Lando Norris', 4, 'McLaren', 'GBR'),
('Oscar Piastri', 81, 'McLaren', 'AUS'),
('Fernando Alonso', 14, 'Aston Martin', 'ESP'),
('Lance Stroll', 18, 'Aston Martin', 'CAN'),
('Esteban Ocon', 31, 'Alpine', 'FRA'),
('Pierre Gasly', 10, 'Alpine', 'FRA'),
('Valtteri Bottas', 77, 'Alfa Romeo', 'FIN'),
('Zhou Guanyu', 24, 'Alfa Romeo', 'CHN'),
('Kevin Magnussen', 20, 'Haas', 'DNK'),
('Nico Hülkenberg', 27, 'Haas', 'DEU'),
('Yuki Tsunoda', 22, 'AlphaTauri', 'JPN'),
('Daniel Ricciardo', 3, 'AlphaTauri', 'AUS'),
('Alexander Albon', 23, 'Williams', 'THA'),
('Logan Sargeant', 2, 'Williams', 'USA');